### ISSUE TITLE
Can we replace "Users" by "Actors" in the Slack messages

### ISSUE THREAD

**Issue by fbraure** [wrapbook/flipper-notifications#8]
The following message may cause confusion. Actors are not always Users. 

```
The feature is now enabled for:
- Users: xxx
```

Is it possible to replace this by something like [flipper-ui:](https://github.com/flippercloud/flipper/blob/d010739e8936034d81368739570153bd99961e12/lib/flipper/ui/views/feature.erb#L78) :

```
settings << "- Actors: #{....decorated_feature.actor_names....sort}
```

Thanks a lot

**Comment by fbraure** [comment]
I have something fonctionnal with:

```
decorated_feature = Flipper::UI::Decorators::Feature.new(feature)
decorated_feature.actor_names = Flipper::UI.configuration.actor_names_source.call(@feature.actors_value)
actors = decorated_feature.actors_value.map do |item|
    decorated_feature.actor_names[item]
end.sort
settings << "- Actors: #{to_sentence(actors)}"
```

**Comment by jdlubrano** [comment]
Hi @fbraure 👋 .  Thanks for your interest in this gem.  My gut reaction is to keep things simpler in this gem, so I would prefer to avoid adding code that relies on Flipper UI and its configuration for actor names.  I see no problem with changing "Users" to "Actors" here, though:

https://github.com/wrapbook/flipper-notifications/blob/c9689a4ed50dec8c5741cce4d291b33671ca0b6e/lib/flipper/notifications/feature_event.rb#L48

We also have actors that are not users, so that maps just fine to our use case as well.  Would that change satisfy your needs?  Or are you especially keen on using Flipper::UI's decorated names?

**Comment by fbraure** [comment]
This change is indeed satisfactory for my use case. Thank you

Alternatively, if you want to display more complete names, without being dependent on Flipper::UI, you can map `flipper_id` which can be redefined in the configuration using Flipper. 

` settings << "- Actors: #{to_sentence(feature.actors.map(&:flipper_id))}" if feature.actors.present? 
`

**Comment by jdlubrano** [comment]
Verbiage has been updated in [v0.1.5](https://github.com/wrapbook/flipper-notifications/releases/tag/v0.1.5).

v0.1.5 has been released to [Rubygems](https://rubygems.org/gems/flipper-notifications).
